services:
  - type: worker
    name: neo2-agent
    runtime: python
    repo: https://github.com/saranya-host/neo2-cloud
    branch: master
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python agent.py"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: LIVEKIT_URL
        sync: false
